require('dotenv').config()

export const env = {
    MONGODB_URI: process.env.MONGODB_URI,
    DATABASE_NAME: process.env.DATABASE_NAME,
    GITHUB_AUTH: process.env.GITHUB_AUTH,
    GITHUB_OWNER: process.env.GITHUB_OWNER,
    GOOGLE_CREDENTIALS_TYPE: process.env.GOOGLE_CREDENTIALS_TYPE,
    GOOGLE_CREDENTIALS_PROJECT_ID: process.env.GOOGLE_CREDENTIALS_PROJECT_ID,
    GOOGLE_CREDENTIALS_PRIVATE_KEY_ID: process.env.GOOGLE_CREDENTIALS_PRIVATE_KEY_ID,
    GOOGLE_CREDENTIALS_PRIVATE_KEY: process.env.GOOGLE_CREDENTIALS_PRIVATE_KEY,
    GOOGLE_CREDENTIALS_CLIENT_EMAIL: process.env.GOOGLE_CREDENTIALS_CLIENT_EMAIL,
    GOOGLE_CREDENTIALS_CLIENT_ID: process.env.GOOGLE_CREDENTIALS_CLIENT_ID,
    GOOGLE_CREDENTIALS_AUTH_URI: process.env.GOOGLE_CREDENTIALS_AUTH_URI,
    GOOGLE_CREDENTIALS_TOKEN_URL: process.env.GOOGLE_CREDENTIALS_TOKEN_URL,
    GOOGLE_CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL: process.env.GOOGLE_CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL,
    GOOGLE_CREDENTIALS_CLIENT_X509_CERT_URL: process.env.GOOGLE_CREDENTIALS_CLIENT_X509_CERT_URL,
    GOOGLE_CREDENTIALS_UNIVERSE_DOMAIN: process.env.GOOGLE_CREDENTIALS_UNIVERSE_DOMAIN,
    RENDER_BEARER_TOKEN: process.env.RENDER_BEARER_TOKEN,
}
