# This is a basic workflow that is manually triggered

name: Github River Backend Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            name:
                # Friendly description to be shown in the UI instead of 'name'
                description: 'CI/CD to greet'
                # Default value if no value is explicitly provided
                default: 'Backend'
                # Input has to be provided for the workflow to run
                required: true
                # The data type of the input
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Send greeting
              run: |
                  echo "Hello ${{ inputs.name }}"
                  echo "Branch ${GITHUB_REF#refs/heads/}"
            - name: Checkout
              uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Code Quality
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.projectKey=river248_ci-cd-github-actions
                      -Dsonar.sources=./backend/src
                      -Dsonar.sourceEncoding=UTF-8
                      -Dsonar.cobol.copy.directories=copybooks
                      -Dsonar.cobol.file.suffixes=cbl,cpy
                      -Dsonar.cobol.copy.suffixes=cpy
                      -Dsonar.flex.cobertura.reportPath=coverage-report/coverage-cobertua-flex.xml
                      -Dsonar.exclusions=**/__tests__/**,**/mocks/** -Dsonar.pli.marginLeft=2
                      -Dsonar.pli.marginRight=0
                      -Dsonar.organization=river248
            - name: Ping Webhook
              run: |
                  echo "Hello ${{ secrets.GITHUB_TOKEN }}"
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/river248/ci-cd-github-actions/hooks/417368240/pings

            - name: Unit Tests
              working-directory: ./backend
              run: |
                  npm ci
                  echo "Running unit tests..."
                  # npm run test
            - name: Unit Test Coverage
              working-directory: ./backend
              run: echo "Reporting unit tests coverage..."
            - name: Generate build folder...
              working-directory: ./backend
              run: npm run build --if-present
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Send greeting
              run: |
                  echo "Hello ${{ inputs.name }}"
                  echo "Branch ${GITHUB_REF#refs/heads/}"
