# This is a basic workflow that is manually triggered

name: Github River Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            BRANCH:
                description: 'Branch to use'
                required: true
                default: 'master'
                type: choice
                options:
                    - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Send greeting
              run: echo "Hello ${{ inputs.name }}"
            - uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - run: npm run build --if-present
        # - run: npm test
