# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "CI/CD to greet"
        # Default value if no value is explicitly provided
        default: "Build"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:
  start_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v7
      - name: Send greeting
        run: echo "Hello ${{ steps.branch-names.outputs.ref_branch }}, I'm in build stage"
  code_quality:
    needs: start_stage
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v7
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-names.outputs.ref_branch }}
      - name: Sonar scanner
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./backend/src
          args: >
            -Dsonar.projectKey=ci-cd-github-actions-backend
            -Dsonar.branch.name=${{ steps.branch-names.outputs.ref_branch }}
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.cobol.copy.directories=copybooks
            -Dsonar.cobol.file.suffixes=cbl,cpy
            -Dsonar.cobol.copy.suffixes=cpy
            -Dsonar.flex.cobertura.reportPath=coverage-report/coverage-cobertua-flex.xml
            -Dsonar.exclusions=**/__tests__/**,**/mocks/** -Dsonar.pli.marginLeft=2
            -Dsonar.pli.marginRight=0
            -Dsonar.organization=river248
      - name: Get sonar report
        id: sonar_report
        run: |
          echo "report=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=ci-cd-github-actions-backend&branch=${{ steps.branch-names.outputs.ref_branch }})" >> "$GITHUB_OUTPUT"
      - name: Push metric
        run: |
          curl -X POST https://6809-118-68-85-98.ngrok-free.app/v1/metric/push-metric?repository=ci-cd-github-actions&&stage=build&executionId=${{ github.run_id }}&metricName=Code%20Quality&appMetricName=backend \
            -H "Content-Type: application/json" \
            -d ${{ toJSON(steps.sonar_report.outputs.report) }}
  unit_tests:
    needs: start_stage
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v7
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-names.outputs.ref_branch }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: unit_tests/backend
        working-directory: ./backend
        run: |
          npm ci
          npm run test
          echo "js_test_cnt=$(xmllint --xpath "string(/testsuites/@tests)" junit.xml)" >> "$GITHUB_OUTPUT"
          echo "js_test_error=$(xmllint --xpath "string(/testsuites/@errors)" junit.xml)" >> "$GITHUB_OUTPUT"
          echo "js_test_failures=$(xmllint --xpath "string(/testsuites/@failures)" junit.xml)" >> "$GITHUB_OUTPUT"
          echo "js_test_success=$(($js_test_cnt - ($js_test_error - $js_test_failures)))" >> "$GITHUB_OUTPUT"
          echo "$js_test_success"
          # curl -X POST https://ff0d-118-68-85-106.ngrok-free.app/v1/metric \
          #  -H "Content-Type: application/json" \
          #  -d '{"repository":"ci-cd-github-actions","stage":"build","executionId":"${{ github.run_id }}","total":1,"actual":1}'
  unit_test_coverage:
    if: ${{ always() }}
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v7
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-names.outputs.ref_branch }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: unit_test_coverage/backend
        working-directory: ./backend
        run: |
          echo "Reporting unit tests coverage..."
          # npm run build --if-present
  finish_stage:
    if: ${{ always() }}
    needs: [code_quality, unit_tests, unit_test_coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v7
      # - name: Checkout branch
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ steps.branch-names.outputs.ref_branch }}
      # - name: Trigger Test
      #   run: |
      #     curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: ${{ secrets.BEARER_TOKEN }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/river248/ci-cd-github-actions/actions/workflows/test.yml/dispatches \
      #       -d '{"ref":"${{ steps.branch-names.outputs.ref_branch }}","inputs":{"name":"Test"}}'
