# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            name:
                # Friendly description to be shown in the UI instead of 'name'
                description: 'CI/CD to greet'
                # Default value if no value is explicitly provided
                default: 'Build'
                # Input has to be provided for the workflow to run
                required: true
                # The data type of the input
                type: string

jobs:
    code_quality:
        runs-on: ubuntu-latest
        steps:
            - name: Send greeting
              run: |
                  echo "Hello ${{ inputs.name }}"
                  echo "Branch ${GITHUB_REF#refs/heads/}"
            - name: Checkout
              uses: actions/checkout@v3
            - name: Sonar Scanner
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.projectKey=river248_ci-cd-github-actions
                      -Dsonar.sources=./backend/src
                      -Dsonar.sourceEncoding=UTF-8
                      -Dsonar.cobol.copy.directories=copybooks
                      -Dsonar.cobol.file.suffixes=cbl,cpy
                      -Dsonar.cobol.copy.suffixes=cpy
                      -Dsonar.flex.cobertura.reportPath=coverage-report/coverage-cobertua-flex.xml
                      -Dsonar.exclusions=**/__tests__/**,**/mocks/** -Dsonar.pli.marginLeft=2
                      -Dsonar.pli.marginRight=0
                      -Dsonar.organization=river248
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Running unit tests...
              working-directory: ./backend
              run: |
                  npm ci
                  # npm run test
    unit_test_coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Generate build folder...
              working-directory: ./backend
              run: |
                  echo "Reporting unit tests coverage..."
                  npm run build --if-present
    move_forward:
        needs: [code_quality, unit_tests, unit_test_coverage]
        uses: ./.github/workflows/test.yml
