# This is a basic workflow that is manually triggered

name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            name:
                # Friendly description to be shown in the UI instead of 'name'
                description: 'CI/CD to greet'
                # Default value if no value is explicitly provided
                default: 'Test'
                # Input has to be provided for the workflow to run
                required: true
                # The data type of the input
                type: string
jobs:
    start_stage:
        runs-on: ubuntu-latest
        steps:
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v7
            - name: Send greeting
              run: echo "Hello ${{ steps.branch-names.outputs.ref_branch }}, I'm in test stage"
    deployment_check:
        needs: start_stage
        runs-on: ubuntu-latest
        steps:
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v7
            - name: Get commit id
              id: commit_id
              run: |
                  echo "value=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
            - name: Trigger a deployment
              id: backend_deployment
              run: |
                  echo deploymentId=$(curl -H "Authorization: ${{ secrets.RENDER_TOKEN }}" -X GET ${{ secrets.RENDER_DEPLOYMENT_TEST_URL }}&ref=${{ steps.commit_id.outputs.value }}) >> "$GITHUB_OUTPUT"
            - name: Get deployment status
              id: deployment_status
              run: |
                  sleep 100s
                  echo report=$(curl -H "Authorization: ${{ secrets.RENDER_TOKEN }}" -X GET https://api.render.com/v1/services/${{ secrets.RENDER_SERVER_TEST_ID }}/deploys/${{ fromJSON(steps.backend_deployment.outputs.deploymentId).deploy.id }}) >> "$GITHUB_OUTPUT"
            - name: Push metric backend
              run: |
                  curl -d '{"repository":"ci-cd-github-actions","stage":"test","executionId":"${{ github.run_id }}","metricName":"Deployment Check","appMetricName":"backend","reportUrl":"https://dashboard.render.com/web/${{ secrets.RENDER_SERVER_TEST_ID }}/events","data":${{ toJSON(steps.deployment_status.outputs.report) }}}' \
                    -H "Content-Type: application/json" \
                    -X POST https://ci-cd-github-actions.onrender.com/v1/metric/push-metric

    finish_stage:
        if: ${{ always() }}
        needs: deployment_check
        runs-on: ubuntu-latest
        steps:
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v7
            - name: Send greeting
              run: echo "Hello ${{ steps.branch-names.outputs.ref_branch }}, I'm fisnishing test stage"
