# This is a basic workflow that is manually triggered

name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            name:
                # Friendly description to be shown in the UI instead of 'name'
                description: 'CI/CD to greet'
                # Default value if no value is explicitly provided
                default: 'Test'
                # Input has to be provided for the workflow to run
                required: true
                # The data type of the input
                type: string
jobs:
    start_stage:
        runs-on: ubuntu-latest
        steps:
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v7
            - name: Send greeting
              run: echo "Hello ${{ steps.branch-names.outputs.ref_branch }}, I'm in test stage"
    deployment_check:
        needs: start_stage
        runs-on: ubuntu-latest
        steps:
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v7
            - name: Generate build folder...
              working-directory: ./backend
              run: npm run build --if-present
    finsish_stage:
        needs: deployment_check
        runs-on: ubuntu-latest
        steps:
            - name: Get branch names.
              id: branch-names
              uses: tj-actions/branch-names@v7
            - name: Send greeting
              run: echo "Hello ${{ steps.branch-names.outputs.ref_branch }}, I'm fisnishing test stage"
    
